### ISSUE TITLE
Name matching error

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-store#17]
This is the record for Thenus orientalis in Sandbox which is loaded correctly:
http://sandbox.ala.org.au/ala-hub/occurrences/ef62647f-97d2-4811-af1b-3964d1e300ff

But same record in the Biocache is matched in different phylum even if there is a taxonomy hint in the DR page for phylum=Arthropoda :
http://biocache.ala.org.au/occurrences/48f5c89d-51a5-4711-96a2-bd0ffa9a2afa

**Comment by adam-collins** [comment]
This appears to be working now.

Sandbox loaded with the raw classification details
```
phylum,order,family,genus,specificEpithet,kingdom,class
Arthropoda,Decapoda,Scyllaridae,Thenus,orientalis,Animalia,Malacostraca
```
to http://sandbox.ala.org.au/ala-hub/occurrences/aecd43a4-df4e-437c-bb50-75b45f1629cc

The phylum is the same and the linked species page is the same http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:b35bf6d6-3b67-4d4c-b81e-b7ca7a64d341

**Comment by sadeghim** [comment]
Still the issue is there. 

If you have a look to the data coming from the web service http://biocache.ala.org.au/ws/occurrences/48f5c89d-51a5-4711-96a2-bd0ffa9a2afa
in the `raw` section :
```javascript
"classification": {
"order": "Decapoda",
"kingdom": "Animalia",
"genus": "Thenus",
"specificEpithet": "orientalis",
"phylum": "Arthropoda",
"family": "Scyllaridae"
},
```
it describes a lobster https://en.wikipedia.org/wiki/Thenus while when biocache processes that assumes this is a bluefin tuna! 

I have specified taxonomic hints to search in Arthropoda phylum but it still doesn't care :(

**Comment by adam-collins** [comment]
Now looking at differences between processed.classification
- Biocache added a vernacularName and sandbox did not. Need a new tool update-commonname-data in biocache-store and run it on sandbox. And run it on biocache because it might be wrong.
- Sandbox added a speciesHabitats "Marine" and biocache did not. Might need to run update-habitat-data on biocache.

Does this seem to describe your problem?

**Comment by sadeghim** [comment]
OK, it seems that the data that I had loaded into sandbox is removed now.
As far as I remember, Sandbox was processing the record correctly, as a lobster while on the ALA it was a Tuna. But it seems that they both function in the same way. Both identify this species incorrectly.

Now I changed the title of the issue to be more relevant to the problem.

**Comment by adam-collins** [comment]
This was confusing because biocache and sandbox were in sync for the name matching. However I did find that using col_namematching index will make an exact match to urn:lsid:catalogueoflife.org:taxon:d2337d5a-2dc5-11e0-98c6-2ce70255a436:col20120124 that is expected.

Likely need to change all apps over at the same time because this is not in bie for example.

Choosing to use common names from the name index would be nice but it appears that the name indexes do not have lsid as an indexed field in the vernacular index so it does not work right now.

**Comment by adam-collins** [comment]
Moved to https://github.com/AtlasOfLivingAustralia/ala-name-matching/issues/24
