### ISSUE TITLE
Processed record date not being set

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#3]
As reported by Reiner:

ISSUE 1
I've noticed some of my records have lost their "date" despite it being
present. For example, the following record shows:
[date not supplied] Year: 2014, Month: 04, Day: Supplied date "2014-04-19"
http://biocache.ala.org.au/occurrences/0be8bff7-c549-4ead-ad93-fb324824acf3

Nick: I've checked the raw vs processed and the processed value is empty. Raw shows: 2014-04-19

**Comment by djtfmartin** [comment]
i scratch my head on this for ages before i realised this is a sensitive record. We remove the day and the complete date information. So we should probably fix this in the UI and instead of saying "[date not supplied]"  add a "Date details removed due to record being sensitive"

cc @M-Nicholls because this came up in another thread recently.

closing
