### ISSUE TITLE
Processing Country values doesn't match State processing

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/biocache-store#68]
I discovered this when I was tracking down some issues with APPD.

The issue is that we process State/Territory boundaries using the 'State plus coastal waters' layer, but the country boundaries layer for processing Country seems to be land mass only.  This produces a significant number of records (around 880k in the ALA) where we have a processed value for State but not for Country... you can see the affected records here:

![ala - bad country value](https://cloud.githubusercontent.com/assets/8856025/9129714/95f26dc2-3d1e-11e5-83a0-42b8eb03e074.JPG)

Not sure if we have a 'countries with territorial waters' layer, but that might be more appropriate to process countries against.  A short term fix alternative might be to add something to the processing so that any record that is identified in a Australian State overrides the processed country value as 'Australia'.

**Comment by adam-collins** [comment]
Setting processed location country to the default country when there is a state for now. Discrepancies between shapefiles are expected and this is reasonable to resolve some of them.

It would be best to move to the actual layer facets instead of using 'state' and 'country' to avoid the inclusion of DwC values.

**Comment by m-hope** [comment]
Thanks Adam... does this mean this feature (setting default country when a state is present) will be included if I reinstall APPD now?  I assume I'd have to reprocess all the data...

If we move to using layers which layer would we use for country (Ie: that includes territorial waters as well as the land mass)?

**Comment by adam-collins** [comment]
It is not in the release yet, so too soon for a reprocess.

If you move to using layers, we do not currently have a countries with territorial waters. For a better match (not perfect because from different sources), use the current states and territories layer without the buffer, cl2013 and world cl932. We are not in the habit of constructing our own contextual layers. Discrepancies can be explained by referring to the layer information, but this is more work for users http://spatial.ala.org.au/layers/more/world http://spatial.ala.org.au/layers/more/asgs_aust_11

When we eventually address this issue https://github.com/AtlasOfLivingAustralia/layers-service/issues/6 there will be a perfect match between new, maybe not the default, state and country layers without an ocean buffer.

I suppose I should ask, is there a need to look at a country facet after restricting to a state?

**Comment by m-hope** [comment]
I think there are other issues with using the non-coastal waters state layer (mainly that you miss all the coastal/marine records), so I think going back to that layer for processing would be a backwards step.

This is mainly an issue of getting significantly different results depending on how you search... if you first search via country and then use the facets to pick a state you are going to get 10% less records that if you search for state initially...

**Comment by adam-collins** [comment]
No intention of changing the layers used in processing for now. Might need to revisit if we get a countries ocean boundaries which would reverse the issue; more in Australia than in States.

I agree that the current use of the state facet can be misleading as it does not indicate in the name that it contains dwc values as well as intersections with a layer having a marine buffer. Moving to using facets that are based on a single layer mean you get what the layer says it is. I also like to add fq=geospatial_kosher:true to anything spatial to remove some of the known issues.
