### ISSUE TITLE
Questagame record date not parsed correctly

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-store#79]
http://biocache.ala.org.au/occurrences/059f8434-4d67-4472-a952-8cc7588a290c

shows raw `eventDate` of `2015-07-09T16:36:00+10:00` but parsed data is:

```
month: "07",
year: "2015"
```

Investigate why date is not being correctly parsed

**Comment by djtfmartin** [comment]
This record is sensitive (hence the date is obscured). Its better represented in the new version

https://biocache-clustered.ala.org.au/occurrences/059f8434-4d67-4472-a952-8cc7588a290c

**Comment by nickdos** [comment]
Is it just me? Still seems odd (and contradictory):

> [date not supplied] Year: 2015, Month: 07, Day: 
> Supplied date "2015-07-09T16:36:00+10:00"

"date not supplied" - then says "supplied date" ???
What's the point of obscuring the processed date when we show the raw date? 

Should I raise a new issue to hide the raw date?

**Comment by djtfmartin** [comment]
No - you can only see the raw date because you have ADMIN privileges. If you logout, its hidden and this is want the public view looks like.

<img width="943" alt="screenshot 2018-05-02 08 45 01" src="https://user-images.githubusercontent.com/444897/39511383-2e3b5c36-4de5-11e8-97ac-ab8a589bac69.png">

I think it could do with better presentation really. 
The "date not supplied" should be removed from display in this instance (i.e. for sensitive records).
